#!/usr/bin/env bash

# https://github.com/aktau/github-release

set -eu

# created setting
tag=$(git tag -l | sort -V | tail -1)
user="maiha"
repo=$(basename `git rev-parse --show-toplevel`)
name=$(basename $repo .cr)
bin=bin/$name
#body="`sha256sum $bin | cut -d' ' -f1` `basename $bin`"

cmd="github-release upload -u $user -r $repo -t $tag -n $name -f $bin"

# env
# [first time] https://github.com/settings/tokens (generate new token with 'repo' scope)
: ${GITHUB_TOKEN?"Need to set GITHUB_TOKEN"}

# check static binary
if file "$bin" | grep statically > /dev/null; then
  : # OK (glibc)
elif ldd "$bin" | grep 'statically linked' > /dev/null; then
  : # OK (musl)
else
  echo "Not statically linked: $bin"
  exit 1
fi

# print cmd as dryrun
echo $cmd

# confirmation
read -p "Are you sure? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo    # (optional) move to a new line
  $cmd
fi
